# Generated by Django 4.2 on 2023-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UN", models.CharField(max_length=225)),
                ("PW", models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="web",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("address", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=225)),
                ("form_no", models.IntegerField()),
                ("current_date", models.CharField(max_length=225)),
                ("s", models.IntegerField()),
                ("cdate", models.CharField(max_length=225)),
                ("cn1", models.CharField(max_length=20)),
                ("cn2", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=225)),
                ("course", models.CharField(max_length=225)),
                ("fa", models.IntegerField()),
                ("ia", models.IntegerField()),
                ("d", models.IntegerField()),
                ("apf", models.IntegerField()),
                ("doi", models.IntegerField()),
                ("rf", models.IntegerField()),
                ("tfp", models.IntegerField()),
                ("ino", models.IntegerField()),
            ],
        ),
    ]
